### ISSUE TITLE
Tinysort not working with Jquery 1.4.2

### ISSUE THREAD

**Issue by Sjeiti** [Sjeiti/TinySort#3]
I've tried using the new JQuery version with tinysort but it seems to not work.
When used it returns this error

this.setArray is not a function:
(function(B){B.tinysort={id:&quot;TinySort&quot;...rt=B.fn.tsort=B.fn.tinysort})(jQuery);<p>Migrated from http://code.google.com/p/tinysort/issues/detail?id=3</p><hr/><h2>earlier comments</h2>

<p><strong>bibendus1983 said, at 2010-05-07T09:02:30.000Z:</strong></p>

<p>Oh, I forgot to say that I'm using TinySort 1.04</p><p><strong>execute.it said, at 2010-06-22T14:02:27.000Z:</strong></p>

<p>I can not confirm the problem. 

jQuery 1.4.2
UI 1.8.2
tinysort 1.0.4
FF 3.6

I hope it also works in all other major browsers.
</p><p><strong>AndresRamirez108 said, at 2010-12-26T05:40:14.000Z:</strong></p>

<p>Update to 1.0.4 fixed that problem for me. I had this issue for a long time and was about to post how I have the same error for any version of jQuery after 1.3.2, but I updated tinysort (right before I posted, from 1.0.2 to .4) and it works!

jQuery 1.4.4
UI 1.8.7
tinysort 1.0.4
FF 3.6.10

Thank you for such nice job with this plugin ;)</p>
